#:schema node_modules/wrangler/config-schema.json
name = "sublink-workerpro"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "848fe793c6f04893a0480b4830663483" }
]

[assets]
directory = "./public"
